// Code generated by MockGen. DO NOT EDIT.
// Source: ./oapi.go
//
// Generated by this command:
//
//	mockgen -destination mocks/oapi_mock.go -package mocks -source ./oapi.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	osc "github.com/outscale/osc-sdk-go/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockOAPIClient is a mock of OAPIClient interface.
type MockOAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockOAPIClientMockRecorder
	isgomock struct{}
}

// MockOAPIClientMockRecorder is the mock recorder for MockOAPIClient.
type MockOAPIClientMockRecorder struct {
	mock *MockOAPIClient
}

// NewMockOAPIClient creates a new mock instance.
func NewMockOAPIClient(ctrl *gomock.Controller) *MockOAPIClient {
	mock := &MockOAPIClient{ctrl: ctrl}
	mock.recorder = &MockOAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAPIClient) EXPECT() *MockOAPIClientMockRecorder {
	return m.recorder
}

// CreateSnapshotExportTask mocks base method.
func (m *MockOAPIClient) CreateSnapshotExportTask(ctx context.Context, req osc.CreateSnapshotExportTaskRequest) (*osc.SnapshotExportTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshotExportTask", ctx, req)
	ret0, _ := ret[0].(*osc.SnapshotExportTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSnapshotExportTask indicates an expected call of CreateSnapshotExportTask.
func (mr *MockOAPIClientMockRecorder) CreateSnapshotExportTask(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshotExportTask", reflect.TypeOf((*MockOAPIClient)(nil).CreateSnapshotExportTask), ctx, req)
}

// ReadSnapshotExportTasks mocks base method.
func (m *MockOAPIClient) ReadSnapshotExportTasks(ctx context.Context, req osc.ReadSnapshotExportTasksRequest) ([]osc.SnapshotExportTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSnapshotExportTasks", ctx, req)
	ret0, _ := ret[0].([]osc.SnapshotExportTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSnapshotExportTasks indicates an expected call of ReadSnapshotExportTasks.
func (mr *MockOAPIClientMockRecorder) ReadSnapshotExportTasks(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSnapshotExportTasks", reflect.TypeOf((*MockOAPIClient)(nil).ReadSnapshotExportTasks), ctx, req)
}
