name: Gitleaks

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: outscale/.github/gitleaks@1f96a7dc5d8e01541f1f6db7f5987afc6ec042c0 # v1.2.0
        with:
          gitleaks-license: ${{ secrets.GITLEAKS_LICENSE }}
