name: Lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint Go + Reuse
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: ⬇️ Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
      - name: 🔎 Golang lint
        uses: outscale/goutils/.github/actions/lint@ba9b0e7bcc1ab4b8fd2c69d8b4de17d86218f5b5 # v1
      - name: 🔎 Reuse lint
        run: |
          make lint-reuse
