name: Unit tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "Makefile"
      - "go.*"
      - ".github/workflows/test.yml"

permissions:
  contents: read

jobs:
  test:
    name: Run Unit tests suite
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: ⬇️ Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: 'go.mod'
      - name: 🧪 Run unit tests
        run: |
          go mod tidy
          make test
